In [1]:
a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))
c = float(input("Enter the third number: "))

largest = max(a, b, c)

print("The largest number is:", largest)

Enter the first number:  22
Enter the second number:  222
Enter the third number:  2222


The largest number is: 2222.0


In [1]:
def is_right_angled(a, b, c):
    # Arrange sides so that c is the largest side
    sides = sorted([a, b, c])
    a, b, c = sides

    # Check the Pythagorean theorem
    return a > 0 and a + b > c and abs((a ** 2 + b ** 2) - c ** 2) < 1e-9


side1 = float(input("Enter the first side: "))
side2 = float(input("Enter the second side: "))
side3 = float(input("Enter the third side: "))

if is_right_angled(side1, side2, side3):
    print("The triangle is right-angled.")
else:
    print("The triangle is not right-angled.")

Enter the first side:  8
Enter the second side:  9
Enter the third side:  7


The triangle is not right-angled.


In [2]:
# Student Data Management Using Python Collections

# Initial student data using dictionary, tuple, and list
# Key: Roll Number (int)
# Value: Tuple (Name, Branch, List of Marks)
students = {
    101: ("Alice", "CSE", [85, 90, 78]),
    102: ("Bob", "ECE", [88, 76, 92]),
    103: ("Charlie", "ME", [70, 75, 80])
}

print("Initial student records:")
for roll, info in students.items():
    name, branch, marks = info
    print(f"Roll: {roll}, Name: {name}, Branch: {branch}, Marks: {marks}")

# 1. Add a new student record
new_roll = 104
new_info = ("Diana", "IT", [82, 88, 91])  # Tuple: (Name, Branch, List of Marks)
students[new_roll] = new_info
print("\nAfter adding new student (Roll 104):")
print(f"Roll: {new_roll}, Name: {new_info[0]}, Branch: {new_info[1]}, Marks: {new_info[2]}")

# 2. Delete an existing student record
del_roll = 102
if del_roll in students:
    deleted = students.pop(del_roll)
    print(f"\nDeleted student (Roll {del_roll}): Name: {deleted[0]}, Branch: {deleted[1]}")
else:
    print(f"\nStudent with Roll {del_roll} not found.")

# 3. Update details of a student
update_roll = 103
if update_roll in students:
    name, branch, marks = students[update_roll]
    # Update branch and add a new mark
    updated_info = (name, "CSE", marks + [85])  # New tuple with updated branch and marks
    students[update_roll] = updated_info
    print(f"\nUpdated student (Roll {update_roll}): Name: {updated_info[0]}, Branch: {updated_info[1]}, Marks: {updated_info[2]}")
else:
    print(f"\nStudent with Roll {update_roll} not found.")

# 4. Display final student records
print("\nFinal student records:")
for roll, info in students.items():
    name, branch, marks = info
    print(f"Roll: {roll}, Name: {name}, Branch: {branch}, Marks: {marks}")
    

Initial student records:
Roll: 101, Name: Alice, Branch: CSE, Marks: [85, 90, 78]
Roll: 102, Name: Bob, Branch: ECE, Marks: [88, 76, 92]
Roll: 103, Name: Charlie, Branch: ME, Marks: [70, 75, 80]

After adding new student (Roll 104):
Roll: 104, Name: Diana, Branch: IT, Marks: [82, 88, 91]

Deleted student (Roll 102): Name: Bob, Branch: ECE

Updated student (Roll 103): Name: Charlie, Branch: CSE, Marks: [70, 75, 80, 85]

Final student records:
Roll: 101, Name: Alice, Branch: CSE, Marks: [85, 90, 78]
Roll: 103, Name: Charlie, Branch: CSE, Marks: [70, 75, 80, 85]
Roll: 104, Name: Diana, Branch: IT, Marks: [82, 88, 91]


In [3]:
import numpy as np

# Create two 3x3 matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Perform matrix addition
C = A + B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nA + B:")
print(C)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

A + B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [ ]:
import re

def validate_pan(pan: str) -> bool:
    """
    Validate PAN number using regular expression.
    Format: AAAAA9999A
    - First 5 characters: uppercase letters (A-Z)
    - Next 4 characters: digits (0-9)
    - Last character: uppercase letter (A-Z)
    """
    pattern = r'^[A-Z]{5}[0-9]{4}[A-Z]$'
    return re.match(pattern, pan) is not None

# Accept PAN number from user
user_pan = input("Enter a PAN number: ").strip()

# Validate and display result
if validate_pan(user_pan):
    print("Valid PAN Number")
else:
    print("Invalid PAN Number")
    